# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.2.5.RELEASE/reference/html/appendix-application-properties.html
# ===================================================================
dubbo:
    registry:
        address: 127.0.0.1:2181
# ===================================================================
# Application specific properties
# ===================================================================
